installCRDs: true
replicaCount: 3
extraArgs:
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
  - --dns01-recursive-nameservers-only
  - --feature-gates=AdditionalCertificateOutputFormats=true
feature-gates: "AdditionalCertificateOutputFormats=true"
webhook:
  extraArgs:
    - --feature-gates=AdditionalCertificateOutputFormats=true
podDnsPolicy: None
podDnsConfig:
  nameservers:
    - "1.1.1.1"
    - "8.8.8.8"
